# feel free to change your base image
FROM fedora:36 

#RUN Something to have jupyterlab and Xeus-cling kernel for example

COPY Test_Notebook.ipynb /work/Test_Notebook.ipynb

WORKDIR /work

EXPOSE 8080

# ENTRYPOINT depends on what you have done before
